import type { Metadata } from "next";
import "./globals.css";
import Header from "./src/reuse-component/Header";
import Footer from "./src/reuse-component/Footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-[#050E12]`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
